# Generated by Django 5.0.1 on 2024-02-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_cart_table_pid_alter_cart_table_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_table',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
