# Generated by Django 4.2.7 on 2024-02-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_cart_table_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_table',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
