# Generated by Django 4.2.7 on 2024-02-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_customerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_table',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='pincode',
            field=models.CharField(max_length=30),
        ),
    ]
